export const SERVICES = [
  {
    id: "1",
    name: "Electrician",
    icon: "Zap",
    startingPrice: 299,
    category: "Repairs",
  },
  {
    id: "2",
    name: "Plumber",
    icon: "Wrench",
    startingPrice: 249,
    category: "Repairs",
  },
  {
    id: "3",
    name: "AC Service",
    icon: "Wind",
    startingPrice: 499,
    category: "Maintenance",
  },
  {
    id: "4",
    name: "Painting",
    icon: "Paintbrush",
    startingPrice: 12,
    category: "Renovation",
  }, // 12/sqft
  {
    id: "5",
    name: "Deep Clean",
    icon: "Sparkles",
    startingPrice: 1499,
    category: "Cleaning",
  },
  {
    id: "6",
    name: "Appliance Repair",
    icon: "MonitorSpeaker",
    startingPrice: 349,
    category: "Repairs",
  },
  {
    id: "7",
    name: "Carpentry",
    icon: "Hammer",
    startingPrice: 499,
    category: "Repairs",
  },
  {
    id: "8",
    name: "Bathroom Repair",
    icon: "Bath",
    startingPrice: 399,
    category: "Repairs",
  },
];

export const REVIEWS = [
  {
    id: "r1",
    reviewer: "Amit Patel",
    rating: 5,
    text: "Very professional, arrived on time!",
    date: "2023-10-12",
  },
  {
    id: "r2",
    reviewer: "Priya Singh",
    rating: 4,
    text: "Good work, fixed the issue quickly.",
    date: "2023-10-10",
  },
  {
    id: "r3",
    reviewer: "Rahul Sharma",
    rating: 5,
    text: "Highly recommend! Great expertise.",
    date: "2023-10-05",
  },
];

export const PROVIDERS = [
  {
    id: "p1",
    name: "Ramesh Kumar",
    trade: "Electrician",
    city: "Mumbai",
    rating: 4.8,
    reviews: 124,
    experience: 8,
    onTimePercent: 95,
    isVerified: true,
    priceMenu: [
      { name: "Fan Repair", price: 299 },
      { name: "Switchboard Fixing", price: 199 },
    ],
  },
  {
    id: "p2",
    name: "Suresh Verma",
    trade: "Plumber",
    city: "Delhi",
    rating: 4.6,
    reviews: 89,
    experience: 5,
    onTimePercent: 92,
    isVerified: true,
    priceMenu: [
      { name: "Tap Repair", price: 199 },
      { name: "Pipe Leakage Fix", price: 349 },
    ],
  },
  {
    id: "p3",
    name: "Vikash Yadav",
    trade: "AC Service",
    city: "Bangalore",
    rating: 4.9,
    reviews: 210,
    experience: 10,
    onTimePercent: 98,
    isVerified: true,
    priceMenu: [
      { name: "AC Regular Service", price: 499 },
      { name: "Gas Refill", price: 1500 },
    ],
  },
  {
    id: "p4",
    name: "Rajeev Singh",
    trade: "Painting",
    city: "Pune",
    rating: 4.5,
    reviews: 65,
    experience: 6,
    onTimePercent: 90,
    isVerified: true,
    priceMenu: [
      { name: "1 Room Painting", price: 2999 },
      { name: "Wall Touchup", price: 999 },
    ],
  },
  {
    id: "p5",
    name: "Anita Das",
    trade: "Deep Clean",
    city: "Kolkata",
    rating: 4.7,
    reviews: 150,
    experience: 4,
    onTimePercent: 96,
    isVerified: true,
    priceMenu: [
      { name: "Bathroom Deep Clean", price: 499 },
      { name: "Kitchen Deep Clean", price: 899 },
    ],
  },
  {
    id: "p6",
    name: "Mohit Chawla",
    trade: "Appliance Repair",
    city: "Chennai",
    rating: 4.4,
    reviews: 45,
    experience: 3,
    onTimePercent: 88,
    isVerified: true,
    priceMenu: [
      { name: "Washing Machine Repair", price: 499 },
      { name: "Refrigerator Repair", price: 599 },
    ],
  },
  {
    id: "p7",
    name: "Dinesh Patel",
    trade: "Carpentry",
    city: "Ahmedabad",
    rating: 4.8,
    reviews: 112,
    experience: 12,
    onTimePercent: 96,
    isVerified: true,
    priceMenu: [
      { name: "Door Repair", price: 499 },
      { name: "Furniture Assembly", price: 899 },
    ],
  },
  {
    id: "p8",
    name: "Karan Mehra",
    trade: "Bathroom Repair",
    city: "Hyderabad",
    rating: 4.6,
    reviews: 78,
    experience: 7,
    onTimePercent: 94,
    isVerified: true,
    priceMenu: [
      { name: "Shower Replacement", price: 299 },
      { name: "Drain Unclogging", price: 399 },
    ],
  },
  {
    id: "p9",
    name: "Sanjay Gupta",
    trade: "Electrician",
    city: "Delhi",
    rating: 4.9,
    reviews: 300,
    experience: 15,
    onTimePercent: 97,
    isVerified: true,
    priceMenu: [
      { name: "Full Home Checkup", price: 499 },
      { name: "MCB Replacement", price: 299 },
    ],
  },
  {
    id: "p10",
    name: "Abdul Rahman",
    trade: "Plumber",
    city: "Mumbai",
    rating: 4.5,
    reviews: 134,
    experience: 6,
    onTimePercent: 91,
    isVerified: true,
    priceMenu: [
      { name: "Washbasin Repair", price: 249 },
      { name: "Toilet Fixing", price: 449 },
    ],
  },
];

export const BOOKINGS = [
  {
    id: "b1",
    serviceId: "1",
    providerId: "p1",
    date: "2023-11-20",
    time: "10:00 AM",
    status: "Confirmed",
    amount: 299,
  },
  {
    id: "b2",
    serviceId: "3",
    providerId: "p3",
    date: "2023-11-21",
    time: "02:00 PM",
    status: "Upcoming",
    amount: 499,
  },
  {
    id: "b3",
    serviceId: "2",
    providerId: "p2",
    date: "2023-10-15",
    time: "11:00 AM",
    status: "Done",
    amount: 249,
  },
  {
    id: "b4",
    serviceId: "5",
    providerId: "p5",
    date: "2023-10-10",
    time: "09:00 AM",
    status: "Done",
    amount: 1499,
  },
  {
    id: "b5",
    serviceId: "8",
    providerId: "p8",
    date: "2023-09-25",
    time: "04:00 PM",
    status: "Done",
    amount: 399,
  },
];
